# Generated by Django 3.2.9 on 2021-12-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='PackImage',
            field=models.ImageField(default='DPlace.jpg', upload_to='Places/'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='PackageDescription',
            field=models.TextField(max_length=200),
        ),
    ]
