# Generated by Django 3.2.7 on 2021-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0002_auto_20211211_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='PackImage',
            new_name='PlaceImage1',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='Days',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='PackageDescription',
        ),
        migrations.AddField(
            model_name='packages',
            name='Activities',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='City',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='Endpoint',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='Exclusions',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='PlaceDescription',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='PlaceImage2',
            field=models.ImageField(default='DPlace.jpg', upload_to='Places/'),
        ),
        migrations.AddField(
            model_name='packages',
            name='PlaceImage3',
            field=models.ImageField(default='DPlace.jpg', upload_to='Places/'),
        ),
        migrations.AddField(
            model_name='packages',
            name='PlaceName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='Startpoint',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='State',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='no_Days',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='stayDetails',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='Amount',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
