# Generated by Django 3.2.7 on 2021-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0003_auto_20211219_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='Country',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='no_Days',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
