# Generated by Django 3.2.7 on 2022-01-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0004_auto_20211219_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='Season',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
