# Generated by Django 3.2.7 on 2022-01-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0006_alter_packages_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Season',
            field=models.CharField(choices=[('', ''), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Monsoon', 'Monsoon'), ('Autumn', 'Autumn'), ('Pre-Winter', 'Pre-Winter'), ('Winter', 'Winter')], default=None, max_length=50, null=True),
        ),
    ]
