# Generated by Django 4.0.4 on 2022-04-28 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TourPackages', '0007_alter_packages_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seats_Available', models.CharField(max_length=5)),
                ('Trip_Start_Date', models.DateTimeField()),
                ('Trip_End_Date', models.DateTimeField()),
                ('Trip_For', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourPackages.packages')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('Transport_Opted', models.CharField(max_length=20)),
                ('Payment_Status', models.CharField(max_length=20)),
                ('No_of_Seats_Applied', models.CharField(max_length=20)),
                ('Applied_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Applied_For', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourPackages.tripinfo')),
            ],
        ),
    ]
