# Generated by Django 4.0.4 on 2022-08-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0008_tripinfo_trip_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinfo',
            name='Trip_status',
            field=models.CharField(choices=[('', ''), ('Planning', 'Planning'), ('Progress', 'Progress'), ('Completed', 'Completed')], default=None, max_length=20),
        ),
    ]
