# Generated by Django 4.0.4 on 2022-08-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0009_tripinfo_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_requests',
            name='Amount',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
