# Generated by Django 4.0.4 on 2022-08-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0010_trip_requests_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Amount',
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
    ]
