# Generated by Django 4.0.4 on 2022-08-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0011_alter_packages_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_requests',
            name='No_of_Seats_Applied',
            field=models.IntegerField(max_length=2),
        ),
    ]
