# Generated by Django 4.0.4 on 2022-08-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0012_alter_trip_requests_no_of_seats_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_requests',
            name='Amount',
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='Seats_Available',
            field=models.IntegerField(max_length=2),
        ),
    ]
