# Generated by Django 4.0.4 on 2022-08-14 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TourPackages', '0013_alter_trip_requests_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_type', models.CharField(choices=[('', ''), ('Car', 'Car'), ('Bike', 'Bike')], default=None, max_length=20, null=True)),
                ('Amount_payable', models.FloatField(default=None, max_length=15, null=True)),
                ('vehicle_req_date', models.DateTimeField(null=True)),
                ('no_of_days_req', models.IntegerField(null=True)),
                ('driving_license', models.FileField(upload_to='Driving_License')),
                ('address', models.TextField(default=None, null=True)),
                ('veh_requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
