# Generated by Django 4.0.4 on 2022-08-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0015_rent_vehicle_remarks_rent_vehicle_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_vehicle',
            name='advance_paid',
            field=models.FloatField(default=None, max_length=15, null=True),
        ),
    ]
