# Generated by Django 4.0.4 on 2022-08-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0016_rent_vehicle_advance_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_vehicle',
            name='remarks',
            field=models.TextField(default=None, null=True),
        ),
    ]
